Pandas Practice

In [1]:
import pandas as pd 
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [2]:
pd.read_csv('./Car_sales.csv')

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [3]:
data = pd.read_csv('./Car_sales.csv')

In [4]:
type(data)

pandas.core.frame.DataFrame

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         157 non-null    object
 1   Model                157 non-null    object
 2   Sales_in_thousands   157 non-null    float64
 3   __year_resale_value  121 non-null    float64
 4   Vehicle_type         157 non-null    object
 5   Price_in_thousands   155 non-null    float64
 6   Engine_size          156 non-null    float64
 7   Horsepower           156 non-null    float64
 8   Wheelbase            156 non-null    float64
 9   Width                156 non-null    float64
 10  Length               156 non-null    float64
 11  Curb_weight          155 non-null    float64
 12  Fuel_capacity        156 non-null    float64
 13  Fuel_efficiency      154 non-null    float64
 14  Latest_Launch        157 non-null    object
 15  Power_perf_factor    155 non-null    float64
dtypes: float64(12), object(4)
memory usage: 19.8+ KB

In [6]:
data.describe()

,Sales_in_thousands,__year_resale_value,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Power_perf_factor
count,157.000000,121.000000,155.000000,156.000000,156.000000,156.000000,156.000000,156.000000,155.000000,156.000000,154.000000,155.000000
mean,52.998076,18.072975,27.390755,3.060897,185.948718,107.487179,71.150000,187.343590,3.378026,17.951923,23.844156,77.043591
std,68.029422,11.453384,14.351653,1.044653,56.700321,7.641303,3.451872,13.431754,0.630502,3.887921,4.282706,25.142664
min,0.110000,5.160000,9.235000,1.000000,55.000000,92.600000,62.600000,149.400000,1.895000,10.300000,15.000000,23.276272
25%,14.114000,11.260000,18.017500,2.300000,149.500000,103.000000,68.400000,177.575000,2.971000,15.800000,21.000000,60.407707
50%,29.450000,14.180000,22.799000,3.000000,177.500000,107.000000,70.550000,187.900000,3.342000,17.200000,24.000000,72.030917
75%,67.956000,19.875000,31.947500,3.575000,215.000000,112.200000,73.425000,196.125000,3.799500,19.575000,26.000000,89.414878
max,540.561000,67.550000,85.500000,8.000000,450.000000,138.700000,79.900000,224.500000,5.572000,32.000000,45.000000,188.144323

In [7]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Sales_in_thousands,157.0,52.998076,68.029422,0.110000,14.114000,29.450000,67.956000,540.561000
__year_resale_value,121.0,18.072975,11.453384,5.160000,11.260000,14.180000,19.875000,67.550000
Price_in_thousands,155.0,27.390755,14.351653,9.235000,18.017500,22.799000,31.947500,85.500000
Engine_size,156.0,3.060897,1.044653,1.000000,2.300000,3.000000,3.575000,8.000000
Horsepower,156.0,185.948718,56.700321,55.000000,149.500000,177.500000,215.000000,450.000000
Wheelbase,156.0,107.487179,7.641303,92.600000,103.000000,107.000000,112.200000,138.700000
Width,156.0,71.150000,3.451872,62.600000,68.400000,70.550000,73.425000,79.900000
Length,156.0,187.343590,13.431754,149.400000,177.575000,187.900000,196.125000,224.500000
Curb_weight,155.0,3.378026,0.630502,1.895000,2.971000,3.342000,3.799500,5.572000
Fuel_capacity,156.0,17.951923,3.887921,10.300000,15.800000,17.200000,19.575000,32.000000
Fuel_efficiency,154.0,23.844156,4.282706,15.000000,21.000000,24.000000,26.000000,45.000000
Power_perf_factor,155.0,77.043591,25.142664,23.276272,60.407707,72.030917,89.414878,188.144323

In [8]:
data.head(12)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
6,Audi,A8,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
7,BMW,323i,19.747,NaN,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
8,BMW,328i,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,1/29/2012,81.877069
9,BMW,528i,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,4/4/2011,83.998724
10,Buick,Century,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,11/2/2011,71.181451
11,Buick,Regal,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,9/3/2011,95.636703

In [9]:
data.tail(3)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
154,Volvo,V70,17.531,NaN,Passenger,28.8,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.5,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.0,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [10]:
data.sample(6)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
39,Dodge,Viper,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,8/7/2011,188.144323
106,Nissan,Xterra,54.158,NaN,Car,22.799,3.3,170.0,104.3,70.4,178.0,3.821,19.4,18.0,1/24/2011,69.782944
70,Lexus,ES300,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,7/9/2012,87.211001
3,Acura,RL,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
9,BMW,528i,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,4/4/2011,83.998724

In [11]:
data.shape

(157, 16)

In [12]:
data.size

2512

In [13]:
data.columns

Index(['Manufacturer', 'Model', 'Sales_in_thousands', '__year_resale_value',
       'Vehicle_type', 'Price_in_thousands', 'Engine_size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb_weight', 'Fuel_capacity',
       'Fuel_efficiency', 'Latest_Launch', 'Power_perf_factor'],
      dtype='object')

In [14]:
data.Model

0      Integra
1           TL
2           CL
3           RL
4           A4
        ...
152        V40
153        S70
154        V70
155        C70
156        S80
Name: Model, Length: 157, dtype: object

In [15]:
data.Manufacturer

0      Acura
1      Acura
2      Acura
3      Acura
4       Audi
       ...
152    Volvo
153    Volvo
154    Volvo
155    Volvo
156    Volvo
Name: Manufacturer, Length: 157, dtype: object

In [16]:
data.Manufacturer.dtype

dtype('O')

Null count:-

In [17]:
data.isnull().sum()

Manufacturer            0
Model                   0
Sales_in_thousands      0
__year_resale_value    36
Vehicle_type            0
Price_in_thousands      2
Engine_size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb_weight             2
Fuel_capacity           1
Fuel_efficiency         3
Latest_Launch           0
Power_perf_factor       2
dtype: int64

In [18]:
data.isnull().mean()*100

Manufacturer            0.000000
Model                   0.000000
Sales_in_thousands      0.000000
__year_resale_value    22.929936
Vehicle_type            0.000000
Price_in_thousands      1.273885
Engine_size             0.636943
Horsepower              0.636943
Wheelbase               0.636943
Width                   0.636943
Length                  0.636943
Curb_weight             1.273885
Fuel_capacity           0.636943
Fuel_efficiency         1.910828
Latest_Launch           0.000000
Power_perf_factor       1.273885
dtype: float64

In [19]:
data.duplicated().sum()

np.int64(0)

In [20]:
data.dropna()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
146,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
147,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
148,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
149,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [21]:
data

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [22]:
data.dropna(inplace=True)

In [23]:
data

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
146,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
147,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
148,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
149,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [24]:
data.drop_duplicates(inplace=True)

In [25]:
data

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
146,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
147,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
148,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
149,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [26]:
data.columns

Index(['Manufacturer', 'Model', 'Sales_in_thousands', '__year_resale_value',
       'Vehicle_type', 'Price_in_thousands', 'Engine_size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb_weight', 'Fuel_capacity',
       'Fuel_efficiency', 'Latest_Launch', 'Power_perf_factor'],
      dtype='object')

In [27]:
data.drop(columns="Width")

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,192.9,3.517,17.2,25.0,6/3/2011,91.370778
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
146,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
147,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
148,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
149,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [28]:
data.drop(columns="Width", inplace=True)

In [29]:
data

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,192.9,3.517,17.2,25.0,6/3/2011,91.370778
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
146,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
147,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
148,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
149,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [30]:
data.reset_index()

,index,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,196.6,3.850,18.0,22.0,3/10/2011,91.389779
3,4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
4,5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,145,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
113,146,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
114,147,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
115,148,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
116,149,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [31]:
data.reset_index(drop=True, inplace=True)

In [32]:
data

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,196.6,3.850,18.0,22.0,3/10/2011,91.389779
3,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
4,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
113,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
114,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
115,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
116,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [33]:
data.loc[7:14]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
7,BMW,528i,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,188.0,3.472,18.5,25.0,4/4/2011,83.998724
8,Buick,Century,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,194.6,3.368,17.5,25.0,11/2/2011,71.181451
9,Buick,Regal,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,196.2,3.543,17.5,23.0,9/3/2011,95.636703
10,Buick,Park Avenue,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,206.8,3.778,18.5,24.0,3/23/2012,85.828408
11,Buick,LeSabre,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,200.0,3.591,17.5,25.0,7/23/2011,84.254526
12,Cadillac,DeVille,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,207.2,3.978,18.5,22.0,2/23/2012,113.854598
13,Cadillac,Eldorado,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,200.6,3.843,19.0,22.0,11/27/2011,113.765874
14,Cadillac,Catera,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,194.8,3.770,18.0,22.0,9/28/2011,83.483094

In [34]:
data.iloc[7:14]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
7,BMW,528i,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,188.0,3.472,18.5,25.0,4/4/2011,83.998724
8,Buick,Century,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,194.6,3.368,17.5,25.0,11/2/2011,71.181451
9,Buick,Regal,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,196.2,3.543,17.5,23.0,9/3/2011,95.636703
10,Buick,Park Avenue,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,206.8,3.778,18.5,24.0,3/23/2012,85.828408
11,Buick,LeSabre,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,200.0,3.591,17.5,25.0,7/23/2011,84.254526
12,Cadillac,DeVille,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,207.2,3.978,18.5,22.0,2/23/2012,113.854598
13,Cadillac,Eldorado,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,200.6,3.843,19.0,22.0,11/27/2011,113.765874

In [35]:
data.iloc[:7]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,196.6,3.850,18.0,22.0,3/10/2011,91.389779
3,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
4,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,192.0,3.561,18.5,22.0,8/9/2011,84.565105
5,Audi,A8,1.380,39.000,Passenger,62.00,4.2,310.0,113.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
6,BMW,328i,9.231,28.675,Passenger,33.40,2.8,193.0,107.3,176.0,3.197,16.6,24.0,1/29/2012,81.877069

In [36]:
data

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,196.6,3.850,18.0,22.0,3/10/2011,91.389779
3,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
4,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
113,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
114,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
115,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
116,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

Calling columns

In [38]:
data.Model

0      Integra
1           TL
2           RL
3           A4
4           A6
        ...
112       Golf
113      Jetta
114     Passat
115     Cabrio
116        GTI
Name: Model, Length: 117, dtype: object

In [39]:
data['Model']

0      Integra
1           TL
2           RL
3           A4
4           A6
        ...
112       Golf
113      Jetta
114     Passat
115     Cabrio
116        GTI
Name: Model, Length: 117, dtype: object

In [40]:
data.Engine_size.value_counts()

Engine_size
2.0    14
3.0    11
1.8     8
3.8     8
4.6     8
2.4     8
2.5     8
4.0     6
3.5     5
3.4     5
3.1     4
3.2     3
1.9     3
3.3     3
2.7     3
2.8     3
3.9     2
2.2     2
2.3     2
4.3     2
1.0     1
8.0     1
5.2     1
5.7     1
1.6     1
1.5     1
4.2     1
5.0     1
4.7     1
Name: count, dtype: int64

In [41]:
data.Engine_size.nunique()

29

In [42]:
data.Engine_size.unique()

array([1.8, 3.2, 3.5, 2.8, 4.2, 3.1, 3.8, 4.6, 3. , 2.2, 3.4, 5.7, 1. ,
       2.5, 2.7, 2. , 8. , 5.2, 3.9, 2.4, 4. , 1.6, 2.3, 1.5, 3.3, 4.3,
       5. , 1.9, 4.7])

In [43]:
data.Price_in_thousands.sum()

np.float64(3038.43)

In [44]:
data.Price_in_thousands.min()

9.235

In [45]:
data.Price_in_thousands.max()

82.6

In [46]:
data.Price_in_thousands.mean()

np.float64(25.969487179487178)

Sorting

In [47]:
data.sort_values(by= 'Horsepower')

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
22,Chevrolet,Metro,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,149.4,1.895,10.3,45.0,4/13/2012,23.276272
52,Hyundai,Accent,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,166.7,2.240,11.9,31.0,9/10/2012,36.672284
102,Saturn,SC,24.546,10.590,Passenger,12.535,1.9,100.0,102.4,180.0,2.367,12.1,33.0,3/16/2011,40.700072
101,Saturn,SL,80.620,9.200,Passenger,10.685,1.9,100.0,102.4,176.9,2.332,12.1,33.0,8/16/2012,39.986425
47,Honda,Civic,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,175.1,2.339,11.9,32.0,10/21/2011,42.879097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Porsche,Carrera Coupe,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,174.5,3.032,17.0,21.0,12/21/2012,134.390975
80,Mercedes-B,SL-Class,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,177.1,4.125,21.1,20.0,3/17/2011,139.982294
5,Audi,A8,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
20,Chevrolet,Corvette,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,179.7,3.210,19.1,22.0,5/12/2012,141.141150
31,Dodge,Viper,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,176.7,3.375,19.0,16.0,8/7/2011,188.144323

In [48]:
data.sort_values(by= 'Horsepower', ascending= False)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
31,Dodge,Viper,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,176.7,3.375,19.0,16.0,8/7/2011,188.144323
20,Chevrolet,Corvette,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,179.7,3.210,19.1,22.0,5/12/2012,141.141150
5,Audi,A8,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
80,Mercedes-B,SL-Class,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,177.1,4.125,21.1,20.0,3/17/2011,139.982294
100,Porsche,Carrera Cabrio,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,174.5,3.075,17.0,23.0,7/11/2011,135.914710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,Honda,Civic,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,175.1,2.339,11.9,32.0,10/21/2011,42.879097
101,Saturn,SL,80.620,9.200,Passenger,10.685,1.9,100.0,102.4,176.9,2.332,12.1,33.0,8/16/2012,39.986425
102,Saturn,SC,24.546,10.590,Passenger,12.535,1.9,100.0,102.4,180.0,2.367,12.1,33.0,3/16/2011,40.700072
52,Hyundai,Accent,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,166.7,2.240,11.9,31.0,9/10/2012,36.672284
22,Chevrolet,Metro,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,149.4,1.895,10.3,45.0,4/13/2012,23.276272

Filtering

In [57]:
data[data["Fuel_capacity"]> 20]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
5,Audi,A8,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
32,Dodge,Ram Pickup,227.061,15.060,Car,19.460,5.2,230.0,138.7,224.2,4.470,26.0,17.0,3/6/2012,90.211700
33,Dodge,Ram Wagon,16.767,15.510,Car,21.315,3.9,175.0,109.6,192.6,4.245,32.0,15.0,1/6/2012,71.135292
34,Dodge,Ram Van,31.038,13.425,Car,18.575,3.9,175.0,127.2,208.5,4.298,32.0,16.0,7/26/2012,70.078322
35,Dodge,Dakota,111.313,11.260,Car,16.980,2.5,120.0,131.0,215.0,3.557,22.0,19.0,11/25/2011,49.645002
42,Ford,Explorer,276.747,16.640,Car,31.930,4.0,210.0,111.6,190.7,3.876,21.0,19.0,4/25/2012,87.635496
43,Ford,Windstar,155.787,13.175,Car,21.410,3.0,150.0,120.7,200.9,3.761,26.0,21.0,2/25/2012,62.095048
44,Ford,Expedition,125.338,23.575,Car,36.135,4.6,240.0,119.0,204.6,4.808,26.0,16.0,9/14/2012,100.024802
46,Ford,F-Series,540.561,15.075,Car,26.935,4.6,220.0,138.5,224.5,4.241,25.1,18.0,8/16/2012,89.401935
50,Honda,Passport,12.855,17.525,Car,26.600,3.2,205.0,106.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
58,Jeep,Grand Cherokee,157.040,18.810,Car,26.895,4.0,195.0,105.9,181.5,3.880,20.5,19.0,12/10/2011,80.387779
61,Lexus,LS400,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,196.7,3.890,22.5,22.0,3/29/2012,124.446716
69,Mitsubishi,Montero,11.337,19.125,Car,31.807,3.5,200.0,107.3,186.6,4.520,24.3,18.0,1/17/2012,83.920815
75,Mercury,Mountaineer,27.609,20.430,Car,27.560,4.0,210.0,111.6,190.1,3.876,21.0,18.0,2/13/2008,85.949744
78,Mercedes-B,E-Class,27.602,41.450,Passenger,49.900,3.2,221.0,111.5,189.4,3.823,21.1,25.0,7/12/2011,98.249737
79,Mercedes-B,S-Class,16.774,50.375,Passenger,69.700,4.3,275.0,121.5,203.1,4.133,23.2,21.0,6/13/2011,125.273876
80,Mercedes-B,SL-Class,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,177.1,4.125,21.1,20.0,3/17/2011,139.982294
85,Nissan,Pathfinder,42.574,17.810,Car,29.299,3.3,170.0,106.3,182.6,3.947,21.0,19.0,9/25/2011,72.290355
89,Oldsmobile,Silhouette,24.361,15.240,Car,25.345,3.4,185.0,120.0,201.4,3.948,25.0,22.0,6/25/2011,76.096570
111,Toyota,Land Cruiser,9.835,34.080,Car,51.728,4.7,230.0,112.2,192.5,5.115,25.4,15.0,9/25/2011,102.528984

In [53]:
data.reset_index()

,index,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,2,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,196.6,3.850,18.0,22.0,3/10/2011,91.389779
3,3,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
4,4,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,112,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
113,113,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
114,114,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
115,115,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
116,116,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [58]:
data_fuel = data[data["Fuel_capacity"]> 20]

In [61]:
data_fuel.drop(columns='Vehicle_type', inplace=True)

In [62]:
data_fuel

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
5,Audi,A8,1.380,39.000,62.000,4.2,310.0,113.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
32,Dodge,Ram Pickup,227.061,15.060,19.460,5.2,230.0,138.7,224.2,4.470,26.0,17.0,3/6/2012,90.211700
33,Dodge,Ram Wagon,16.767,15.510,21.315,3.9,175.0,109.6,192.6,4.245,32.0,15.0,1/6/2012,71.135292
34,Dodge,Ram Van,31.038,13.425,18.575,3.9,175.0,127.2,208.5,4.298,32.0,16.0,7/26/2012,70.078322
35,Dodge,Dakota,111.313,11.260,16.980,2.5,120.0,131.0,215.0,3.557,22.0,19.0,11/25/2011,49.645002
42,Ford,Explorer,276.747,16.640,31.930,4.0,210.0,111.6,190.7,3.876,21.0,19.0,4/25/2012,87.635496
43,Ford,Windstar,155.787,13.175,21.410,3.0,150.0,120.7,200.9,3.761,26.0,21.0,2/25/2012,62.095048
44,Ford,Expedition,125.338,23.575,36.135,4.6,240.0,119.0,204.6,4.808,26.0,16.0,9/14/2012,100.024802
46,Ford,F-Series,540.561,15.075,26.935,4.6,220.0,138.5,224.5,4.241,25.1,18.0,8/16/2012,89.401935
50,Honda,Passport,12.855,17.525,26.600,3.2,205.0,106.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
58,Jeep,Grand Cherokee,157.040,18.810,26.895,4.0,195.0,105.9,181.5,3.880,20.5,19.0,12/10/2011,80.387779
61,Lexus,LS400,6.375,40.375,54.005,4.0,290.0,112.2,196.7,3.890,22.5,22.0,3/29/2012,124.446716
69,Mitsubishi,Montero,11.337,19.125,31.807,3.5,200.0,107.3,186.6,4.520,24.3,18.0,1/17/2012,83.920815
75,Mercury,Mountaineer,27.609,20.430,27.560,4.0,210.0,111.6,190.1,3.876,21.0,18.0,2/13/2008,85.949744
78,Mercedes-B,E-Class,27.602,41.450,49.900,3.2,221.0,111.5,189.4,3.823,21.1,25.0,7/12/2011,98.249737
79,Mercedes-B,S-Class,16.774,50.375,69.700,4.3,275.0,121.5,203.1,4.133,23.2,21.0,6/13/2011,125.273876
80,Mercedes-B,SL-Class,3.311,58.600,82.600,5.0,302.0,99.0,177.1,4.125,21.1,20.0,3/17/2011,139.982294
85,Nissan,Pathfinder,42.574,17.810,29.299,3.3,170.0,106.3,182.6,3.947,21.0,19.0,9/25/2011,72.290355
89,Oldsmobile,Silhouette,24.361,15.240,25.345,3.4,185.0,120.0,201.4,3.948,25.0,22.0,6/25/2011,76.096570
111,Toyota,Land Cruiser,9.835,34.080,51.728,4.7,230.0,112.2,192.5,5.115,25.4,15.0,9/25/2011,102.528984

In [63]:
data

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,196.6,3.850,18.0,22.0,3/10/2011,91.389779
3,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
4,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
113,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
114,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
115,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
116,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [64]:
data_fuel

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
5,Audi,A8,1.380,39.000,62.000,4.2,310.0,113.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858
32,Dodge,Ram Pickup,227.061,15.060,19.460,5.2,230.0,138.7,224.2,4.470,26.0,17.0,3/6/2012,90.211700
33,Dodge,Ram Wagon,16.767,15.510,21.315,3.9,175.0,109.6,192.6,4.245,32.0,15.0,1/6/2012,71.135292
34,Dodge,Ram Van,31.038,13.425,18.575,3.9,175.0,127.2,208.5,4.298,32.0,16.0,7/26/2012,70.078322
35,Dodge,Dakota,111.313,11.260,16.980,2.5,120.0,131.0,215.0,3.557,22.0,19.0,11/25/2011,49.645002
42,Ford,Explorer,276.747,16.640,31.930,4.0,210.0,111.6,190.7,3.876,21.0,19.0,4/25/2012,87.635496
43,Ford,Windstar,155.787,13.175,21.410,3.0,150.0,120.7,200.9,3.761,26.0,21.0,2/25/2012,62.095048
44,Ford,Expedition,125.338,23.575,36.135,4.6,240.0,119.0,204.6,4.808,26.0,16.0,9/14/2012,100.024802
46,Ford,F-Series,540.561,15.075,26.935,4.6,220.0,138.5,224.5,4.241,25.1,18.0,8/16/2012,89.401935
50,Honda,Passport,12.855,17.525,26.600,3.2,205.0,106.4,178.2,3.857,21.1,19.0,10/9/2012,83.602501
58,Jeep,Grand Cherokee,157.040,18.810,26.895,4.0,195.0,105.9,181.5,3.880,20.5,19.0,12/10/2011,80.387779
61,Lexus,LS400,6.375,40.375,54.005,4.0,290.0,112.2,196.7,3.890,22.5,22.0,3/29/2012,124.446716
69,Mitsubishi,Montero,11.337,19.125,31.807,3.5,200.0,107.3,186.6,4.520,24.3,18.0,1/17/2012,83.920815
75,Mercury,Mountaineer,27.609,20.430,27.560,4.0,210.0,111.6,190.1,3.876,21.0,18.0,2/13/2008,85.949744
78,Mercedes-B,E-Class,27.602,41.450,49.900,3.2,221.0,111.5,189.4,3.823,21.1,25.0,7/12/2011,98.249737
79,Mercedes-B,S-Class,16.774,50.375,69.700,4.3,275.0,121.5,203.1,4.133,23.2,21.0,6/13/2011,125.273876
80,Mercedes-B,SL-Class,3.311,58.600,82.600,5.0,302.0,99.0,177.1,4.125,21.1,20.0,3/17/2011,139.982294
85,Nissan,Pathfinder,42.574,17.810,29.299,3.3,170.0,106.3,182.6,3.947,21.0,19.0,9/25/2011,72.290355
89,Oldsmobile,Silhouette,24.361,15.240,25.345,3.4,185.0,120.0,201.4,3.948,25.0,22.0,6/25/2011,76.096570
111,Toyota,Land Cruiser,9.835,34.080,51.728,4.7,230.0,112.2,192.5,5.115,25.4,15.0,9/25/2011,102.528984

In [66]:
data_fuel.drop(columns= ['Power_perf_factor','__year_resale_value',  'Sales_in_thousands'], inplace=True)

In [67]:
data_fuel

,Manufacturer,Model,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch
5,Audi,A8,62.000,4.2,310.0,113.0,198.2,3.902,23.7,21.0,2/27/2012
32,Dodge,Ram Pickup,19.460,5.2,230.0,138.7,224.2,4.470,26.0,17.0,3/6/2012
33,Dodge,Ram Wagon,21.315,3.9,175.0,109.6,192.6,4.245,32.0,15.0,1/6/2012
34,Dodge,Ram Van,18.575,3.9,175.0,127.2,208.5,4.298,32.0,16.0,7/26/2012
35,Dodge,Dakota,16.980,2.5,120.0,131.0,215.0,3.557,22.0,19.0,11/25/2011
42,Ford,Explorer,31.930,4.0,210.0,111.6,190.7,3.876,21.0,19.0,4/25/2012
43,Ford,Windstar,21.410,3.0,150.0,120.7,200.9,3.761,26.0,21.0,2/25/2012
44,Ford,Expedition,36.135,4.6,240.0,119.0,204.6,4.808,26.0,16.0,9/14/2012
46,Ford,F-Series,26.935,4.6,220.0,138.5,224.5,4.241,25.1,18.0,8/16/2012
50,Honda,Passport,26.600,3.2,205.0,106.4,178.2,3.857,21.1,19.0,10/9/2012
58,Jeep,Grand Cherokee,26.895,4.0,195.0,105.9,181.5,3.880,20.5,19.0,12/10/2011
61,Lexus,LS400,54.005,4.0,290.0,112.2,196.7,3.890,22.5,22.0,3/29/2012
69,Mitsubishi,Montero,31.807,3.5,200.0,107.3,186.6,4.520,24.3,18.0,1/17/2012
75,Mercury,Mountaineer,27.560,4.0,210.0,111.6,190.1,3.876,21.0,18.0,2/13/2008
78,Mercedes-B,E-Class,49.900,3.2,221.0,111.5,189.4,3.823,21.1,25.0,7/12/2011
79,Mercedes-B,S-Class,69.700,4.3,275.0,121.5,203.1,4.133,23.2,21.0,6/13/2011
80,Mercedes-B,SL-Class,82.600,5.0,302.0,99.0,177.1,4.125,21.1,20.0,3/17/2011
85,Nissan,Pathfinder,29.299,3.3,170.0,106.3,182.6,3.947,21.0,19.0,9/25/2011
89,Oldsmobile,Silhouette,25.345,3.4,185.0,120.0,201.4,3.948,25.0,22.0,6/25/2011
111,Toyota,Land Cruiser,51.728,4.7,230.0,112.2,192.5,5.115,25.4,15.0,9/25/2011

Groupby

In [70]:
data.groupby(['Manufacturer'])['Price_in_thousands'].mean().reset_index()

   Manufacturer  Price_in_thousands
0         Acura           30.633333
1          Audi           39.980000
2           BMW           36.150000
3         Buick           26.781250
4      Cadillac           36.856667
5     Chevrolet           20.164375
6      Chrysler           22.280000
7         Dodge           24.170556
8          Ford           21.920500
9         Honda           20.277000
10      Hyundai           12.165667
11     Infiniti           29.465000
12         Jeep           20.991667
13        Lexus           41.105000
14      Lincoln           41.205000
15   Mercedes-B           58.487500
16      Mercury           20.748333
17   Mitsubishi           22.167429
18       Nissan           23.167200
19   Oldsmobile           27.829250
20     Plymouth           15.856667
21      Pontiac           22.412000
22      Porsche           62.473333
23       Saturn           12.503333
24       Toyota           21.934750
25   Volkswagen           18.058000

In [72]:
data.groupby(['Manufacturer','Model'])['Horsepower'].sum()

Manufacturer  Model
Acura         Integra    140.0
              RL         210.0
              TL         225.0
Audi          A4         150.0
              A6         200.0
                         ...
Volkswagen    Cabrio     115.0
              GTI        115.0
              Golf       115.0
              Jetta      115.0
              Passat     150.0
Name: Horsepower, Length: 117, dtype: float64

In [73]:
data.groupby(['Manufacturer','Model'])['Horsepower'].sum().reset_index()

    Manufacturer    Model  Horsepower
0          Acura  Integra       140.0
1          Acura       RL       210.0
2          Acura       TL       225.0
3           Audi       A4       150.0
4           Audi       A6       200.0
..           ...      ...         ...
112   Volkswagen   Cabrio       115.0
113   Volkswagen      GTI       115.0
114   Volkswagen     Golf       115.0
115   Volkswagen    Jetta       115.0
116   Volkswagen   Passat       150.0

[117 rows x 3 columns]

In [74]:
data

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,196.6,3.850,18.0,22.0,3/10/2011,91.389779
3,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
4,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
113,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
114,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
115,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
116,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [76]:
data.query("Manufacturer=='Volkswagen'")

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
112,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
113,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
114,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
115,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
116,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [79]:
data.query("Horsepower < 200")

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,172.4,2.639,13.2,28.0,2/2/2012,58.280150
3,Audi,A4,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,178.0,2.998,16.4,27.0,10/8/2011,62.777639
6,BMW,328i,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,176.0,3.197,16.6,24.0,1/29/2012,81.877069
7,BMW,528i,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,188.0,3.472,18.5,25.0,4/4/2011,83.998724
8,Buick,Century,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,194.6,3.368,17.5,25.0,11/2/2011,71.181451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Volkswagen,Golf,9.761,11.425,Passenger,14.900,2.0,115.0,98.9,163.3,2.767,14.5,26.0,1/24/2011,46.943877
113,Volkswagen,Jetta,83.721,13.240,Passenger,16.700,2.0,115.0,98.9,172.3,2.853,14.5,26.0,8/27/2011,47.638237
114,Volkswagen,Passat,51.102,16.725,Passenger,21.200,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381
115,Volkswagen,Cabrio,9.569,16.575,Passenger,19.990,2.0,115.0,97.4,160.4,3.079,13.7,26.0,5/31/2011,48.907372
116,Volkswagen,GTI,5.596,13.760,Passenger,17.500,2.0,115.0,98.9,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [86]:
data.query("Manufacturer == 'Volkswagen' & Engine_size < 2.0 & Fuel_capacity >= 15")

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
114,Volkswagen,Passat,51.102,16.725,Passenger,21.2,1.8,150.0,106.4,184.1,3.043,16.4,27.0,10/30/2012,61.701381

Pivot()

In [88]:
data.pivot_table(values = "Price_in_thousands", index = "Vehicle_type", columns = "Fuel_efficiency", aggfunc = 'sum')

Fuel_efficiency,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,45.0
Vehicle_type,,,,,,,,,,,,,,,,,,,,
Car,73.043,54.710,33.92,86.302,163.302,44.147,70.319,25.345,71.866,58.965,NaN,NaN,16.888,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Passenger,NaN,69.725,NaN,NaN,NaN,82.600,316.300,427.966,197.920,250.257,437.16,148.63,176.677,37.74,25.28,56.096,40.864,12.885,50.288,9.235

In [90]:
data.pivot_table(values = "Price_in_thousands", index = "Vehicle_type", columns = "Fuel_efficiency", aggfunc = 'sum', margins=True)

Fuel_efficiency,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,...,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,45.0,All
Vehicle_type,,,,,,,,,,,,,,,,,,,,,
Car,73.043,54.710,33.92,86.302,163.302,44.147,70.319,25.345,71.866,58.965,...,NaN,16.888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,698.807
Passenger,NaN,69.725,NaN,NaN,NaN,82.600,316.300,427.966,197.920,250.257,...,148.63,176.677,37.74,25.28,56.096,40.864,12.885,50.288,9.235,2339.623
All,73.043,124.435,33.92,86.302,163.302,126.747,386.619,453.311,269.786,309.222,...,148.63,193.565,37.74,25.28,56.096,40.864,12.885,50.288,9.235,3038.430